config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'lists', to: 'lists#index'
  get 'lists/new', to: 'lists#new'
  get 'lists/:id', to: 'lists#show', as: 'list'
  post 'lists', to: 'lists#create'
  delete 'lists', to: 'lists#destroy', as: 'delete_list'
  get 'lists/:id/bookmarks/new', to: 'bookmarks#new', as: 'new_bookmark'
  post 'lists/:id/bookmarks', to: 'bookmarks#create', as: 'list_bookmarks'
  resources :bookmarks, only: [:destroy]
end

# A user can see all the lists
# GET "lists"
# A user can see the details of a given list and its name
# GET "lists/42"
# A user can create a new list
# GET "lists/new"
# POST "lists"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
  # A bookmark must be linked to a movie and a list,
  # and the [movie, list] pairings should be unique.
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:id])
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :conflict
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    # @bookmark = @list.bookmark
    # @list.movies = @bookmarks.movie
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booksmarks_helper.rb
module BooksmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Booksmarks#new</h1>
<p>Find me in app/views/booksmarks/new.html.erb</p>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, as: :select %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div id="banner">
  <h1>WATCH LIST</h1>
  <a href="#"><%= link_to 'new list', lists_new_path %></a>
</div>
<% @lists.each do |list| %>
  <div class="card">
    <% if list.photo.attached? %>
      <a href="#"><%= cl_image_tag list.photo.key, height: 150, width: 200, crop: :fill %></a>
    <% end %>
    <h1><%= link_to list.name.upcase, list_path(list) %></h1>
    <button><%= link_to 'Delete', delete_list_path(list) %></button>
  </div>
<% end %>
<br>

app/views/lists/new.html.erb
<h1>Create a new list</h1>
<p>Just time in your name for the list</p>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<a href="#"><%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %></a>

<div class='card' style="width: 35rem;">
  <% if @list.movies %>
    <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(movie: movie, list: @list) %>
    <div class='card-img-top'>
      <%= image_tag "#{movie.poster_url}", alt: "#{movie.title}", width: 200 %>
    </div>
    <div class='card-body'>
      <h5 class='card-title'><%= movie.title%></h5>
      <h5 class='card-title'><%= movie.rating%></h5>
      <p class='card-text'><%= movie.overview %></p>
      <p class='card-text'><%= bookmark.comment %></p>
      <a href="#" class='card-link'><%= link_to 'delete', bookmark_path(bookmark),
       data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </div>
    <% end %>
  <% else %>
    <p>No movies added yet</p>
  <% end %>
</div>

<button><%= link_to 'Add new movie to list', new_bookmark_path %></button>
<button><%= link_to 'Back', lists_path %></button>